# Run me by typing `mythx analyze` in the directory of the yml file! :)

ci: true
confirm: true
analyze:
    mode: quick
    async: true
    create-group: true
    solc: 0.6.12
    remappings:
        - "@openzeppelin=node_modules/@openzeppelin"
    targets:
        - contracts/SushiMaker.sol:SushiMaker
        - contracts/tacoswapv2/TacoswapV2Pair.sol:TacoswapV2Pair
        - contracts/tacoswapv2/TacoswapV2Factory.sol:TacoswapV2Factory
        - contracts/tacoswapv2/TacoswapV2ERC20.sol:TacoswapV2ERC20
        - contracts/tacoswapv2/TacoswapV2Router02.sol:TacoswapV2Router02
        - contracts/SushiRoll.sol:SushiRoll
        - contracts/SushiToken.sol:SushiToken
        - contracts/SushiBar.sol:SushiBar
        - contracts/MasterChef.sol:MasterChef
        - contracts/governance/Timelock.sol:Timelock
        - contracts/Migrator.sol:Migrator
